insert into {betriebsauswertung_schema}.{betriebsauswertung_tabel}(
	jahr,
	monat,
	anzahl_kuhe_durchsnit_monat,
	anzahl_melkend_durchsnit_monat,
	anzahl_trocken_durchsnit_monat,
	anzahl_1_laktation_durchsnit_monat,
	anzahl_kalbungen,
	remontierung_pct,
	anzahl_kalbungen_faersen,
	anzahl_abgang_30_tg,
	pzt_abgang_30_tg,
	anzahl_abgang_60_tg,
	pzt_abgang_60_tg,
	anzahl_abgang_1_laktation,
	pzt_abgang_1_laktation,
	anzahl_verkauft,
	anzahl_verendet,
	anzahl_tragend_durchsnit_monat,
	anzahl_150_nicht_tragend_durchsnit_monat,
	anzahl_zu_durchsnit_monat,
	laktationstage_durchsnit_monat,
	anzahl_gruppe_ek_durchsnit_monat,
	sperrmilch,
	anzahl_besamungen,
	anzahl_totgeburten,
	anzahl_totgeburten_faersen,
	anzahl_mastitis_erstbehandlung,
	anzahl_mastitis_nachbehandlung,
	anzahl_nachgeburtsverhaltung,
	anzahl_lm,
	anzahl_gebaerparese)
select {jahr}, {monat}, bta.*
from functions.betriebsauswertung({jahr}, {monat}, '{pg_schema}') bta;
